"""Fast tier for fifo_almost_full_2cycle_read -- cocotb + Verilator.

This is the PR gate from docs/verification_plan.md Sec.2: it runs in seconds,
needs no license, and every test below traces to a numbered behavior in
docs/fifo_spec.md Sec.4. Each test's docstring opens with a machine-greppable
``Spec: F..`` line so the traceability matrix in verification_plan.md Sec.1
stays checkable by grep rather than by memory -- the Python-side equivalent of
``begin_test(name, specs)`` in the Questa tier.

Timing convention (the thing to get right before reading anything else)
----------------------------------------------------------------------
Every cycle of stimulus goes through ``Fifo.cycle()``, which drives the inputs,
waits the rising edge that consumes them, steps the reference model, then reads
the DUT back at the *falling* edge. Reading at the falling edge matters: cocotb
resumes from ``RisingEdge`` before the non-blocking updates from that edge have
landed, so a value read there is the *pre-edge* value. Half a period later
everything has settled and the RTL has no negedge-sensitive logic, so a falling
edge read is race-free without needing a ``ReadOnly`` phase -- and it leaves us
in a writable phase, so the next cycle's stimulus can be driven immediately.

Because driver and checker are the same loop, there is no forked monitor that
could sample an input the test has already overwritten. Every cycle is checked,
not just the checkpoints.

Read-data timing (F13). For a read accepted at edge E, the RAM output register
picks the word up at E and the second output register publishes it at E+1, so
``rd_data`` holds it from the falling edge of the cycle *after* acceptance. The
Questa tier's ``a_read_latency`` writes the same fact as ``##2`` because SVA
samples pre-edge; the two conventions differ by one edge and describe the same
pipeline. Getting this off by one is exactly the bug class the scoreboard
exists to catch, which is why the expectation is generated by a model with its
own pipeline rather than by a "wait N cycles then look" helper.

Parameters come from the environment (set by tb/cocotb/Makefile alongside the
matching Verilator ``-G`` overrides) so the same file runs against every
elaboration in the sweep. ``make sweep`` is what closes F10: at the
``ALMOST_FULL_THRESHOLD == DEPTH`` default, exact-match and threshold-and-above
``almost_full`` are indistinguishable.
"""

from __future__ import annotations

import logging
import os
import random
from collections import deque
from dataclasses import dataclass

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import FallingEdge, RisingEdge

log = logging.getLogger("fifo_tb")


def _env_int(name: str, default: int) -> int:
    raw = os.environ.get(name)
    if raw is None or raw == "":
        return int(default)
    return int(raw)


WIDTH = _env_int("FIFO_WIDTH", 8)
DEPTH = _env_int("FIFO_DEPTH", 32)
ALMOST_FULL_THRESHOLD = _env_int("FIFO_AF_THRESHOLD", DEPTH)
NUM_TESTS = _env_int("FIFO_NUM_TESTS", 2000)
SEED = _env_int("FIFO_SEED", 1)

CLK_PERIOD_NS = 10
MAX_ERRORS = 25
DATA_MASK = (1 << WIDTH) - 1

# Drive random garbage on wr_data whenever wr_en is low (the Questa tier's
# TOGGLE_INPUTS_WHILE_IDLE). A DUT that latched write data without qualifying it
# on wr_en && !full would corrupt the stream and get caught by the scoreboard.
TOGGLE_INPUTS_WHILE_IDLE = True


@dataclass
class Snapshot:
    """DUT state as of the falling edge following edge N -- fully settled."""

    count: int
    full: int
    empty: int
    almost_full: int
    rd_data: int
    wr_addr: int | None
    rd_addr: int | None


@dataclass
class CycleRecord:
    """What the model decided for one edge, kept for the F16 window check."""

    acc_rd: bool
    empty_before: bool
    rst: bool
    rd_data: int


class FifoModel:
    """Reference model derived from docs/fifo_spec.md, not from the RTL.

    The two acceptance lines below look identical to the RTL's
    ``valid_wr``/``valid_rd`` and must not be maintained by copying them from
    it. That distinction is not stylistic: verification_plan.md Sec.4 records an
    F7 mismatch that stayed invisible to every per-cycle check in the Questa
    tier precisely because its model had inherited ``wr_en && !full`` from the
    implementation. A model that inherits the implementation's acceptance rule
    cannot detect a bug in that rule.

    Spec rules encoded here:
      F2/F4/F7 -- a write commits iff ``wr_en`` and occupancy != DEPTH, with no
                  dependence on whether a read commits in the same cycle.
      F3/F5/F8 -- a read commits iff ``rd_en`` and occupancy != 0, likewise
                  independent of the write.
      F10      -- ``almost_full`` is exact match on the threshold, not >=.
      F13      -- one pipeline stage of expectation delay under this file's
                  falling-edge sampling convention (see the module docstring).
      F14      -- strict FIFO ordering, from the queue itself.
    """

    def __init__(self) -> None:
        self.q: deque[int] = deque()
        self.wr_idx = 0
        self.rd_idx = 0
        self.wr_wraps = 0
        self.rd_wraps = 0
        # Expectation pipeline. `pending` is the word dequeued by the previous
        # edge; `matured` is what rd_data must show at the snapshot taken after
        # the edge just applied.
        self.pending: int | None = None
        self.matured: int | None = None
        self.accepted_writes = 0
        self.accepted_reads = 0

    def step(self, rst: int, wr: int, rd: int, data: int) -> CycleRecord:
        occ_before = len(self.q)

        if rst:
            # F1/F15: pointers and count clear regardless of prior occupancy.
            self.q.clear()
            self.wr_idx = 0
            self.rd_idx = 0
            self.pending = None
            self.matured = None
            # The read pipeline is deliberately NOT reset in the RTL
            # (fifo_spec.md Sec.3), so a word in flight would still land
            # correctly. The model drops it anyway: under the no-valid-signal
            # consumer contract that word is never sampled, and asserting on it
            # would be checking a guarantee the design does not make.
            return CycleRecord(acc_rd=False, empty_before=occ_before == 0, rst=True, rd_data=0)

        # What rd_data must show after this edge: the word dequeued one edge ago.
        self.matured = self.pending

        # Both decisions are taken from the occupancy *before* this edge, so the
        # pop/push order below cannot affect the outcome. That
        # ordering-independence is what makes F6, F7 and F8 fall out of two
        # lines instead of three special cases.
        acc_rd = bool(rd) and occ_before != 0
        acc_wr = bool(wr) and occ_before != DEPTH

        self.pending = None
        if acc_rd:
            self.pending = self.q.popleft()  # F14: strict FIFO order
            self.rd_idx = (self.rd_idx + 1) % DEPTH
            if self.rd_idx == 0:
                self.rd_wraps += 1  # F9
            self.accepted_reads += 1
        if acc_wr:
            self.q.append(data & DATA_MASK)
            self.wr_idx = (self.wr_idx + 1) % DEPTH
            if self.wr_idx == 0:
                self.wr_wraps += 1  # F9
            self.accepted_writes += 1

        return CycleRecord(acc_rd=acc_rd, empty_before=occ_before == 0, rst=False, rd_data=0)

    # --- expectations ----------------------------------------------------
    @property
    def occupancy(self) -> int:
        return len(self.q)

    @property
    def exp_full(self) -> int:
        return int(len(self.q) == DEPTH)

    @property
    def exp_empty(self) -> int:
        return int(len(self.q) == 0)

    @property
    def exp_almost_full(self) -> int:
        # F10: exact match. `>=` would pass at the THRESHOLD == DEPTH default
        # and fail everywhere else -- see the note in test_almost_full_threshold.
        return int(len(self.q) == ALMOST_FULL_THRESHOLD)


def _resolve(handle, what: str) -> int:
    """int() a handle, but fail loudly on X/Z instead of silently reading 0."""
    value = handle.value
    text = str(value).lower()
    if "x" in text or "z" in text:
        raise AssertionError(f"{what} is unresolvable ({value})")
    return int(value)


class Fifo:
    """Driver, reference model and checker for one test, in a single loop."""

    def __init__(self, dut) -> None:
        self.dut = dut
        self.model = FifoModel()
        self.rnd = random.Random(SEED)
        self.errors: list[str] = []
        self.data_checks = 0
        self.armed = False  # no checking until a reset has been applied
        self._window: deque[CycleRecord] = deque(maxlen=3)
        self._stim_data = 0
        self.last: Snapshot | None = None

        if DEPTH < 2 or (DEPTH & (DEPTH - 1)) != 0:
            raise AssertionError(f"DEPTH must be a power of 2 and >= 2 (got {DEPTH})")
        if not 1 <= ALMOST_FULL_THRESHOLD <= DEPTH:
            raise AssertionError(
                f"ALMOST_FULL_THRESHOLD must be in [1, {DEPTH}] (got {ALMOST_FULL_THRESHOLD})"
            )

        # Cross-check the environment against the elaborated design, so a
        # Makefile whose -G overrides and FIFO_* variables drift apart fails
        # here rather than silently verifying a different design than the one
        # the results file names.
        #
        # Deliberately checked through signal widths, not by reading the
        # parameters: Verilator constant-folds parameters out of the model
        # entirely, and its VPI then reports each one's *declared default*
        # rather than the elaborated -G value. Reading dut.DEPTH.value gives 32
        # even in a build whose almost_full compare folded to `4U == count_r`,
        # so a parameter read here would be a false failure, not a safety net.
        # Widths survive the folding, and since DEPTH must be a power of two,
        # count's width pins it exactly.
        try:
            widths = {
                "wr_data": len(dut.wr_data),
                "rd_data": len(dut.rd_data),
                "count": len(dut.count),
            }
        except Exception:  # pragma: no cover - simulator without width info
            widths = {}
        if widths:
            # $clog2(DEPTH+1); for a power-of-two DEPTH that is log2(DEPTH)+1.
            exp_count_width = DEPTH.bit_length()
            for name in ("wr_data", "rd_data"):
                if widths[name] != WIDTH:
                    raise AssertionError(
                        f"elaboration mismatch: {name} is {widths[name]} bits, testbench expects "
                        f"WIDTH={WIDTH}. Check the -G overrides in tb/cocotb/Makefile."
                    )
            if widths["count"] != exp_count_width:
                raise AssertionError(
                    f"elaboration mismatch: count is {widths['count']} bits, testbench expects "
                    f"{exp_count_width} for DEPTH={DEPTH}. Check the -G overrides in "
                    "tb/cocotb/Makefile."
                )
        # ALMOST_FULL_THRESHOLD has no width to check against. A mismatch there
        # surfaces immediately anyway: the per-cycle almost_full comparison
        # fails on the first cycle the two thresholds disagree, and
        # test_almost_full_threshold names the mismatch explicitly.

        # F2/F3/F9 pointer cross-check, when the simulator exposes the internals.
        self.check_ptrs = True
        try:
            int(dut.wr_addr_r.value)
            int(dut.rd_addr_r.value)
        except Exception:
            self.check_ptrs = False
            log.warning("wr_addr_r/rd_addr_r not visible; skipping pointer checks (F2/F3/F9)")

    # --- plumbing --------------------------------------------------------
    def next_data(self) -> int:
        self._stim_data = (self._stim_data + 1) & DATA_MASK
        return self._stim_data

    async def start(self) -> None:
        cocotb.start_soon(Clock(self.dut.clk, CLK_PERIOD_NS, unit="ns").start())
        self.dut.rst.value = 1
        self.dut.wr_en.value = 0
        self.dut.rd_en.value = 0
        self.dut.wr_data.value = 0
        # Land in the second half of a cycle so cycle() always drives from a
        # writable phase that precedes the edge which consumes the values.
        await FallingEdge(self.dut.clk)

    def _sample(self) -> Snapshot:
        d = self.dut
        return Snapshot(
            count=_resolve(d.count, "count"),
            full=_resolve(d.full, "full"),
            empty=_resolve(d.empty, "empty"),
            almost_full=_resolve(d.almost_full, "almost_full"),
            rd_data=int(d.rd_data.value),  # not reset by design; may be X pre-first-read
            wr_addr=int(d.wr_addr_r.value) if self.check_ptrs else None,
            rd_addr=int(d.rd_addr_r.value) if self.check_ptrs else None,
        )

    def _fail(self, msg: str) -> None:
        self.errors.append(msg)
        log.error(msg)
        if len(self.errors) >= MAX_ERRORS:
            raise AssertionError(f"aborting after {len(self.errors)} failures:\n" + "\n".join(self.errors))

    def check_no_errors(self) -> None:
        if self.errors:
            raise AssertionError(f"{len(self.errors)} check(s) failed:\n" + "\n".join(self.errors))

    async def cycle(self, wr: int = 0, rd: int = 0, data: int | None = None, rst: int = 0) -> Snapshot:
        """Drive one cycle, advance the model, check the DUT. Returns the snapshot."""
        d = self.dut
        if data is None:
            data = self.next_data() if wr else 0
        driven = data if (wr or not TOGGLE_INPUTS_WHILE_IDLE) else self.rnd.getrandbits(WIDTH)

        d.rst.value = rst
        d.wr_en.value = wr
        d.rd_en.value = rd
        d.wr_data.value = driven

        await RisingEdge(d.clk)          # this edge consumes what we just drove
        record = self.model.step(rst, wr, rd, data)
        if rst:
            self.armed = True
        await FallingEdge(d.clk)         # settled, and back in a writable phase

        snap = self._sample()
        self.last = snap
        record.rd_data = snap.rd_data
        self._window.append(record)
        if self.armed:
            self._check(snap)
            self._check_no_bubble()
        return snap

    def _check(self, snap: Snapshot) -> None:
        m = self.model
        occ = m.occupancy

        # F2-F9: occupancy accounting under every interleaving.
        if snap.count != occ:
            self._fail(f"count = {snap.count}, expected {occ}")
        if snap.full != m.exp_full:  # F4/F11
            self._fail(f"full = {snap.full}, expected {m.exp_full} (count={occ})")
        if snap.empty != m.exp_empty:  # F5/F12
            self._fail(f"empty = {snap.empty}, expected {m.exp_empty} (count={occ})")
        if snap.almost_full != m.exp_almost_full:  # F10
            self._fail(
                f"almost_full = {snap.almost_full}, expected {m.exp_almost_full} "
                f"(count={occ}, THRESHOLD={ALMOST_FULL_THRESHOLD})"
            )

        # F2/F3/F9: pointers advance only on committed accesses, and wrap mod DEPTH.
        if self.check_ptrs:
            if snap.wr_addr != m.wr_idx:
                self._fail(f"wr_addr_r = {snap.wr_addr}, expected {m.wr_idx}")
            if snap.rd_addr != m.rd_idx:
                self._fail(f"rd_addr_r = {snap.rd_addr}, expected {m.rd_idx}")

        # F13/F14: the word dequeued one edge ago is on rd_data now, and it is
        # the right word. Expected and actual are produced by two independent
        # derivations, so a latency change breaks the value comparison rather
        # than quietly passing.
        if m.matured is not None:
            self.data_checks += 1
            if snap.rd_data != m.matured:
                self._fail(
                    f"rd_data = 0x{snap.rd_data:0{(WIDTH + 3) // 4}x}, "
                    f"expected 0x{m.matured:0{(WIDTH + 3) // 4}x} (check #{self.data_checks})"
                )

    def _check_no_bubble(self) -> None:
        """F16: no read accepted at edge M leaves rd_data unchanged at M+2.

        With no accepted read the read address does not move, so ``rd_data_ram``
        re-reads the same word and the output register cannot publish a bubble.
        Two guards, both load-bearing and both matching the Questa tier's
        ``a_read_pipeline_no_bubble``:

        * ``empty_before`` -- while empty, a write can land on the very address
          the read pointer is parked on, so rd_data legitimately changes with no
          accepted read. Inconsequential under the fifo_spec.md Sec.3 consumer
          contract, but it is not a bubble and must not be flagged as one.
        * ``rst`` -- reset returns the read address to 0, so it can change what
          the pipeline picks up with no accepted read (F15). Expected, not a
          bubble.
        """
        if len(self._window) < 3:
            return
        a, b, c = self._window[0], self._window[1], self._window[2]
        if a.acc_rd or a.empty_before or a.rst or b.rst:
            return
        if b.rd_data != c.rd_data:
            self._fail(
                f"rd_data changed 0x{b.rd_data:x} -> 0x{c.rd_data:x} with no accepted read (F16)"
            )

    # --- stimulus helpers -------------------------------------------------
    async def reset(self, cycles: int = 3) -> None:
        for _ in range(cycles):
            await self.cycle(rst=1)
        await self.cycle()  # first edge with rst deasserted

    async def idle(self, n: int = 1) -> None:
        for _ in range(n):
            await self.cycle()

    async def fill(self, n: int) -> None:
        for _ in range(n):
            await self.cycle(wr=1)

    async def drain(self, n: int) -> None:
        for _ in range(n):
            await self.cycle(rd=1)

    def expect_state(self, ctx: str, count: int) -> None:
        """Explicit checkpoint on top of the per-cycle checks, so a failure names
        the test's intent rather than only the cycle it happened on."""
        snap = self.last
        assert snap is not None, "expect_state() before any cycle"
        exp_full = int(count == DEPTH)
        exp_empty = int(count == 0)
        exp_af = int(count == ALMOST_FULL_THRESHOLD)
        assert snap.count == count, f"{ctx}: count={snap.count}, expected {count}"
        assert snap.full == exp_full, f"{ctx}: full={snap.full}, expected {exp_full}"
        assert snap.empty == exp_empty, f"{ctx}: empty={snap.empty}, expected {exp_empty}"
        assert snap.almost_full == exp_af, f"{ctx}: almost_full={snap.almost_full}, expected {exp_af}"


async def setup(dut) -> Fifo:
    tb = Fifo(dut)
    log.info(
        "WIDTH=%d DEPTH=%d ALMOST_FULL_THRESHOLD=%d NUM_TESTS=%d seed=%d",
        WIDTH,
        DEPTH,
        ALMOST_FULL_THRESHOLD,
        NUM_TESTS,
        SEED,
    )
    await tb.start()
    await tb.reset()
    return tb


# ---------------------------------------------------------------------------
# Tests. One per docs/verification_plan.md Sec.2, same set and same names as the
# Questa tier so a spec ID is covered by the same-named test on both sides.
# ---------------------------------------------------------------------------


@cocotb.test()
async def test_reset(dut):
    """Spec: F1 -- reset clears count and both pointers, from a non-trivial state."""
    tb = await setup(dut)

    # Put something in first, so the reset has state to clear rather than
    # passing trivially from a cold start.
    await tb.fill(DEPTH // 2)
    tb.expect_state("before reset", DEPTH // 2)

    await tb.reset()
    tb.expect_state("after reset", 0)
    if tb.check_ptrs:
        assert tb.last.wr_addr == 0, f"wr_addr_r={tb.last.wr_addr} after reset"
        assert tb.last.rd_addr == 0, f"rd_addr_r={tb.last.rd_addr} after reset"

    # rd_data is deliberately NOT checked here: fifo_spec.md Sec.3 excludes the
    # read pipeline from reset, so asserting rd_data == 0 would be asserting a
    # guarantee the design does not make.
    tb.check_no_errors()


@cocotb.test()
async def test_fill_to_full(dut):
    """Spec: F2, F4, F10 -- writes commit and count reaches DEPTH, then full holds."""
    tb = await setup(dut)

    for i in range(DEPTH):
        snap = await tb.cycle(wr=1)
        assert snap.count == i + 1, f"count={snap.count} after {i + 1} writes"

    tb.expect_state("filled", DEPTH)
    assert tb.last.full == 1

    # F4: further writes while full are dropped and do not advance the pointer.
    wr_addr_at_full = tb.last.wr_addr
    await tb.cycle(wr=1)
    tb.expect_state("write while full", DEPTH)
    if tb.check_ptrs:
        assert tb.last.wr_addr == wr_addr_at_full, "write pointer moved while full"

    tb.check_no_errors()


@cocotb.test()
async def test_drain_to_empty(dut):
    """Spec: F3, F5, F10 -- reads commit in order and count returns to 0."""
    tb = await setup(dut)

    await tb.fill(DEPTH)
    tb.expect_state("filled", DEPTH)

    for i in range(DEPTH):
        snap = await tb.cycle(rd=1)
        assert snap.count == DEPTH - i - 1, f"count={snap.count} after {i + 1} reads"

    tb.expect_state("drained", 0)

    # F5: further reads while empty are dropped.
    rd_addr_at_empty = tb.last.rd_addr
    await tb.cycle(rd=1)
    tb.expect_state("read while empty", 0)
    if tb.check_ptrs:
        assert tb.last.rd_addr == rd_addr_at_empty, "read pointer moved while empty"

    await tb.idle(2)  # let the last read mature so the scoreboard sees it
    tb.check_no_errors()


@cocotb.test()
async def test_pointer_wrap(dut):
    """Spec: F9 -- both pointers wrap mod DEPTH; occupancy stays correct across >=2 wraps."""
    tb = await setup(dut)

    # Half-fill first so the two pointers wrap at different times rather than in
    # lockstep -- a model that tracked only their difference would pass a
    # lockstep test.
    await tb.fill(DEPTH // 2)

    for _ in range(2 * DEPTH + DEPTH // 2):
        await tb.cycle(wr=1, rd=1)

    await tb.drain(DEPTH // 2)
    await tb.idle(2)

    assert tb.model.wr_wraps >= 2, f"write pointer wrapped {tb.model.wr_wraps} times, need >= 2"
    assert tb.model.rd_wraps >= 2, f"read pointer wrapped {tb.model.rd_wraps} times, need >= 2"
    tb.expect_state("after wraps", 0)
    tb.check_no_errors()


@cocotb.test()
async def test_simultaneous_rw_mid(dut):
    """Spec: F6 -- wr+rd while neither full nor empty: both commit, count unchanged."""
    tb = await setup(dut)

    await tb.fill(DEPTH // 2)
    tb.expect_state("half full", DEPTH // 2)

    for _ in range(DEPTH):
        snap = await tb.cycle(wr=1, rd=1)
        assert snap.count == DEPTH // 2, f"count={snap.count}, expected {DEPTH // 2} (F6)"

    await tb.drain(DEPTH // 2)
    await tb.idle(2)
    tb.check_no_errors()


@cocotb.test()
async def test_simultaneous_rw_at_full(dut):
    """Spec: F7 -- wr+rd while full: the read commits, the write is dropped.

    This is the case that caught the spec/RTL mismatch recorded in
    verification_plan.md Sec.4, and it caught it only because it is directed.
    The per-cycle count comparison stayed silent (the Questa model had inherited
    `wr_en && !full` from the RTL) and `a_no_overflow` is qualified on `!rd_en`
    so it never evaluated here. Occupancy settling at DEPTH-1 rather than DEPTH
    is the observable consequence.
    """
    tb = await setup(dut)

    await tb.fill(DEPTH)
    tb.expect_state("full", DEPTH)

    # First simultaneous cycle at full: the write is dropped, so the slot the
    # read frees is not refilled.
    snap = await tb.cycle(wr=1, rd=1)
    assert snap.count == DEPTH - 1, f"count={snap.count}, expected {DEPTH - 1} (F7)"

    # Sustained: no longer full, so both commit every cycle and occupancy sits
    # at DEPTH-1. One slot of effective depth, no throughput loss, no data loss.
    for _ in range(DEPTH):
        snap = await tb.cycle(wr=1, rd=1)
        assert snap.count == DEPTH - 1, f"count={snap.count}, expected {DEPTH - 1} under sustained rw"

    await tb.drain(DEPTH - 1)
    await tb.idle(2)
    tb.expect_state("drained", 0)
    tb.check_no_errors()


@cocotb.test()
async def test_simultaneous_rw_at_empty(dut):
    """Spec: F8 -- wr+rd while empty: the write commits, the read is dropped."""
    tb = await setup(dut)
    tb.expect_state("empty", 0)

    snap = await tb.cycle(wr=1, rd=1)
    assert snap.count == 1, f"count={snap.count}, expected 1 (F8)"

    # And the word that went in is the one that comes back out -- proof the
    # dropped read did not consume it.
    await tb.cycle(rd=1)
    await tb.idle(2)
    tb.expect_state("drained", 0)
    tb.check_no_errors()


@cocotb.test()
async def test_write_while_full_no_read(dut):
    """Spec: F4, F11 -- sustained writes while full corrupt nothing already stored."""
    tb = await setup(dut)

    await tb.fill(DEPTH)
    tb.expect_state("full", DEPTH)
    wr_addr_at_full = tb.last.wr_addr

    for _ in range(DEPTH):
        snap = await tb.cycle(wr=1)
        assert snap.count == DEPTH, f"count={snap.count} under sustained back-pressure (F11)"
        if tb.check_ptrs:
            assert snap.wr_addr == wr_addr_at_full, "write pointer moved while full"

    # Reading it all back is what actually proves the stored data survived: the
    # scoreboard compares every word against the model's queue, which never
    # accepted any of the dropped writes.
    await tb.drain(DEPTH)
    await tb.idle(2)
    tb.expect_state("drained", 0)
    assert tb.data_checks >= DEPTH, f"only {tb.data_checks} rd_data checks, expected >= {DEPTH}"
    tb.check_no_errors()


@cocotb.test()
async def test_read_while_empty_no_write(dut):
    """Spec: F5, F12 -- sustained reads while empty return no data and move nothing."""
    tb = await setup(dut)
    tb.expect_state("empty", 0)

    rd_addr_at_empty = tb.last.rd_addr
    held = tb.last.rd_data
    for _ in range(DEPTH):
        snap = await tb.cycle(rd=1)
        assert snap.count == 0, f"count={snap.count} under sustained underflow (F12)"
        assert snap.empty == 1
        if tb.check_ptrs:
            assert snap.rd_addr == rd_addr_at_empty, "read pointer moved while empty"
        # F12: rd_data holds its previous value; no data enters the pipeline.
        assert snap.rd_data == held, f"rd_data changed to 0x{snap.rd_data:x} while empty"

    tb.check_no_errors()


@cocotb.test()
async def test_reset_mid_burst(dut):
    """Spec: F15 -- reset with entries stored and a read in flight clears pointers and count."""
    tb = await setup(dut)

    await tb.fill(DEPTH // 2)
    await tb.cycle(rd=1)  # a word is now in flight in the read pipeline
    assert tb.last.count == DEPTH // 2 - 1

    await tb.reset()
    tb.expect_state("after mid-burst reset", 0)
    if tb.check_ptrs:
        assert tb.last.wr_addr == 0, f"wr_addr_r={tb.last.wr_addr} after mid-burst reset"
        assert tb.last.rd_addr == 0, f"rd_addr_r={tb.last.rd_addr} after mid-burst reset"

    # Whatever was in flight is left as-is by design (fifo_spec.md Sec.3), so
    # the real proof that reset worked is that the FIFO behaves from scratch
    # afterwards -- including returning the first post-reset word, not a
    # leftover one.
    await tb.cycle(wr=1, data=0xA5 & DATA_MASK)
    await tb.cycle(rd=1)
    await tb.idle(2)
    tb.expect_state("post-reset traffic", 0)
    tb.check_no_errors()


@cocotb.test()
async def test_back_to_back_reads(dut):
    """Spec: F13 -- one read accepted per cycle despite the 2-stage read pipeline."""
    tb = await setup(dut)

    await tb.fill(DEPTH)
    tb.expect_state("full", DEPTH)

    reads_before = tb.model.accepted_reads
    checks_before = tb.data_checks

    for i in range(DEPTH):
        snap = await tb.cycle(rd=1)
        # No throughput loss: exactly one entry leaves per cycle. A design that
        # stalled for the extra pipeline stage would decrement every other cycle.
        assert snap.count == DEPTH - i - 1, (
            f"count={snap.count} on back-to-back read {i}, expected {DEPTH - i - 1}"
        )

    assert tb.model.accepted_reads - reads_before == DEPTH, "not one accepted read per cycle"

    await tb.idle(2)  # flush the pipeline so the last words get compared
    # Every one of those reads was checked for value and for arrival cycle by
    # the per-cycle scoreboard; this asserts none of them silently went missing.
    assert tb.data_checks - checks_before == DEPTH, (
        f"{tb.data_checks - checks_before} rd_data checks for {DEPTH} reads"
    )
    tb.check_no_errors()


@cocotb.test()
async def test_read_pipeline_bubble(dut):
    """Spec: F16 -- rd_data never shows a bubble on cycles with no accepted read.

    Covers both ways a read fails to be accepted: rd_en deasserted, and rd_en
    asserted while empty (F5/F8). The continuous check in Fifo._check_no_bubble
    is running underneath this the whole time; the directed sequence below is
    what guarantees the interesting windows actually occur.
    """
    tb = await setup(dut)

    # Case 1: rd_en deasserted, FIFO non-empty.
    await tb.fill(DEPTH // 2)
    await tb.cycle(rd=1)  # accepted read at this edge

    values = []
    for _ in range(6):
        values.append((await tb.cycle()).rd_data)
    # values[0] is the read's own data arriving one edge after acceptance; from
    # there the read address is parked, so everything after it must be identical.
    assert len(set(values[1:])) == 1, f"rd_data not held with no accepted read: {[hex(v) for v in values]}"

    # Case 2: rd_en asserted but dropped because the FIFO is empty.
    await tb.drain(DEPTH // 2 - 1)
    await tb.idle(3)
    tb.expect_state("empty", 0)

    held = tb.last.rd_data
    for _ in range(6):
        snap = await tb.cycle(rd=1)
        assert snap.rd_data == held, f"rd_data changed to 0x{snap.rd_data:x} on a dropped read"

    tb.check_no_errors()


@cocotb.test()
async def test_almost_full_threshold(dut):
    """Spec: F10 -- almost_full is exact match: it asserts at the threshold and
    deasserts again above it.

    Walks occupancy one entry at a time from 0 to DEPTH and back, recording the
    flag at every occupancy, then asserts the set of occupancies where it was
    high is exactly {ALMOST_FULL_THRESHOLD}. Checking only that it asserts *at*
    the threshold would pass for a `>=` flag too; the deassertion above it is
    the whole difference.
    """
    tb = await setup(dut)

    if ALMOST_FULL_THRESHOLD == DEPTH:
        log.info(
            "NOTE: ALMOST_FULL_THRESHOLD == DEPTH, so exact-match and "
            "threshold-and-above almost_full are indistinguishable in this "
            "elaboration. `make sweep` runs THRESHOLD=1 and DEPTH/2 as well; "
            "F10 is not closed by this run alone (verification_plan.md Sec.4)."
        )

    seen: dict[int, int] = {}

    await tb.idle(1)
    seen[0] = tb.last.almost_full

    for _ in range(DEPTH):  # walk up
        snap = await tb.cycle(wr=1)
        seen[tb.model.occupancy] = snap.almost_full

    for _ in range(DEPTH):  # walk back down
        snap = await tb.cycle(rd=1)
        occ = tb.model.occupancy
        # Only record if the walk up did not already disagree -- it must not.
        if occ in seen and seen[occ] != snap.almost_full:
            tb._fail(f"almost_full={snap.almost_full} at occupancy {occ} on the way down, "
                     f"but {seen[occ]} on the way up")
        seen[occ] = snap.almost_full

    missing = [occ for occ in range(DEPTH + 1) if occ not in seen]
    assert not missing, f"occupancies never visited by the walk: {missing}"

    high = sorted(occ for occ, flag in seen.items() if flag)
    assert high == [ALMOST_FULL_THRESHOLD], (
        f"almost_full was high at occupancies {high}, expected exactly "
        f"[{ALMOST_FULL_THRESHOLD}] -- an exact-match flag, not >= (F10)"
    )

    await tb.idle(2)
    tb.check_no_errors()


@cocotb.test()
async def test_random_stress(dut):
    """Spec: F11, F12, F14 -- randomized traffic against the reference model.

    Weights sweep across the run -- write-heavy, then balanced, then read-heavy
    -- so the FIFO actually sits at full and at empty under sustained pressure.
    A single balanced distribution spends nearly all its time mid-occupancy and
    reaches neither extreme reliably.
    """
    tb = await setup(dut)
    log.info("random stress: %d transactions, seed=%d (rerun with FIFO_SEED=%d)", NUM_TESTS, SEED, SEED)

    for i in range(NUM_TESTS):
        if i < NUM_TESTS // 3:
            wr_weight, rd_weight = 85, 30  # toward full  -> F11
        elif i < (2 * NUM_TESTS) // 3:
            wr_weight, rd_weight = 55, 55  # balanced     -> F6/F9/F14
        else:
            wr_weight, rd_weight = 25, 85  # toward empty -> F12

        wr = int(tb.rnd.randrange(100) < wr_weight)
        rd = int(tb.rnd.randrange(100) < rd_weight)
        await tb.cycle(wr=wr, rd=rd)

        # Back-to-back traffic is what stresses a FIFO, so gaps stay rare.
        if tb.rnd.randrange(100) < 20:
            await tb.idle(tb.rnd.randint(1, 9))

    # Drain whatever is left so the trailing words get their ordering checked.
    await tb.drain(DEPTH)
    await tb.idle(3)
    tb.expect_state("drained", 0)

    m = tb.model
    log.info(
        "accepted writes=%d reads=%d | rd_data checks=%d | wraps wr=%d rd=%d",
        m.accepted_writes,
        m.accepted_reads,
        tb.data_checks,
        m.wr_wraps,
        m.rd_wraps,
    )
    # A stress run that never reached the extremes proves much less than it
    # looks like it does, so say so rather than passing quietly.
    assert m.wr_wraps >= 2 and m.rd_wraps >= 2, (
        f"stress run wrapped only wr={m.wr_wraps} rd={m.rd_wraps} times (F9 wants >= 2); "
        "raise FIFO_NUM_TESTS or lower FIFO_DEPTH"
    )
    assert tb.data_checks > 0
    tb.check_no_errors()
